export const FILMS_TYPES = Object.freeze({
    SET_FILMS: 'SET_FILMS',
    RESET_FILMS: 'RESET_FILMS',
    START_LOADING: 'START_LOADING',
    CHANGE_PAGE: 'CHANGE_PAGE',
    RESET_PAGE: 'RESET_PAGE',
    SET_MAX_PAGE: 'SET_MAX_PAGE',
    TOGGLE_GENRE: 'TOGGLE_GENRE',
    SET_GENRES: 'SET_GENRES',
    SET_SORT: 'SET_SORT',
    SET_DATE_FROM: 'SET_DATE_FROM',
    SET_DATE_TO: 'SET_DATE_TO',
    SET_RATING: 'SET_RATING',
    SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
    RESET_FILTERS: 'RESET_FILTERS',
})

export const FILM_TYPES = Object.freeze({
    SET_FILM: 'SET_FILM',
    START_FILM_LOADING: 'START_FILM_LOADING',
    RESET_FILM: 'RESET_FILM',
})

export const ERRORS_TYPES = Object.freeze({
    SET_ERROR: 'SET_ERROR',
    RESET_ERRORS: 'RESET_ERRORS',
    DELETE_ERROR: 'DELETE_ERROR'
})

export const AUTH_TYPES = Object.freeze({
    LOG_IN: 'LOG_IN',
    LOG_OUT: 'LOG_OUT'
})
